site_name: Analog Devices MSDK Documentation
docs_dir: 'Documentation'
site_dir: 'docs'
nav:
  - Home: 'index.md'
  - User Guide: 'USERGUIDE.md'
  - Contributing: 'CONTRIBUTING.md'
theme:
  name: readthedocs
markdown_extensions:
  codehilite:
    use_pygments: False