/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// qrcode_tinierssd_nobias
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78000/CNN --prefix qrcode_tinierssd_nobias --checkpoint-file QRCode/ai85-qrcode-tinierssd-nobias-qat8-q.pth.tar --config-file QRCode/ai85-qrcode-tinierssd.yaml --sample-input QRCode/sample_qrcode.npy --fifo --device MAX78000 --timer 0 --display-checkpoint --verbose

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "rtc.h"

#include "tft_ssd2119.h"

#include "camera.h"
#include "camera_utils.h"

#include "post_process.h"
// #include "sampledata.h"
// #include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// Data input: HWC 3x240x320 (230400 bytes total / 76800 bytes per channel):
// static const uint32_t input_0[] = SAMPLE_INPUT_0;
void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  int i;
  //const uint32_t *in0 = input_0;

  for (i = 0; i < 76800; i++) {
    // Remove the following line if there is no risk that the source would overrun the FIFO:
    while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
    *((volatile uint32_t *) 0x50000008) = 0;//*in0++; // Write FIFO 0
  }
}

// Expected output of layer 13, 14, 15, 16, 17, 18, 19, 20 for qrcode_tinierssd_nobias given the sample input (known-answer test)
// Delete this function for production code
// static const uint32_t sample_output[] = SAMPLE_OUTPUT;
// int check_output(void)
// {
//   int i;
//   uint32_t mask, len;
//   volatile uint32_t *addr;
//   const uint32_t *ptr = sample_output;

//   while ((addr = (volatile uint32_t *) *ptr++) != 0) {
//     mask = *ptr++;
//     len = *ptr++;
//     for (i = 0; i < len; i++)
//       if ((*addr++ & mask) != *ptr++) {
//         printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
//                i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
//         return CNN_FAIL;
//       }
//   }

//   return CNN_OK;
// }

static int32_t ml_data32[(CNN_NUM_OUTPUTS + 3) / 4];

int main(void)
{
  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  // Initialize RTC
  MXC_RTC_Init(0, 0);
  MXC_RTC_Start();

  initialize_camera();

  // Initialize TFT display.
  printf("Init TFT\n");
  MXC_TFT_Init();
  MXC_TFT_ClearScreen();
  MXC_Delay(SEC(2));

  printf("Waiting...\n");

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test qrcode_tinierssd_nobias_ds_input ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();

  while(1){
    printf("Start capturing\n");
    cnn_configure(); // Configure state 
    cnn_start(); // Start CNN processing
    load_camera_input();

    while (cnn_time == 0)
      MXC_LP_EnterSleepMode(); // Wait for CNN

#ifdef CNN_INFERENCE_TIMER
    printf("Approximate data loading and inference time: %u us\n\n", cnn_time);
#endif

    check_for_all_zero_output();

    get_priors();
    nms();
    display_camera();
    print_detected_boxes();
  }

  cnn_disable(); // Shut down CNN clock, disable peripheral

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 1,728,946,640 ops (1,717,787,520 macc; 11,159,120 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 68,812,800 ops (66,355,200 macc; 2,457,600 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 710,246,400 ops (707,788,800 macc; 2,457,600 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 357,580,800 ops (353,894,400 macc; 3,686,400 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 178,483,200 ops (176,947,200 macc; 1,536,000 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 177,254,400 ops (176,947,200 macc; 307,200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 44,620,800 ops (44,236,800 macc; 384,000 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 44,313,600 ops (44,236,800 macc; 76,800 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7: 88,627,200 ops (88,473,600 macc; 153,600 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8 (fire8): 44,275,200 ops (44,236,800 macc; 38,400 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9 (fire9): 2,812,800 ops (2,764,800 macc; 48,000 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10 (fire10): 656,320 ops (645,120 macc; 11,200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11: 323,680 ops (322,560 macc; 1,120 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12 (conv12_2): 35,760 ops (34,560 macc; 1,200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13: 5,529,600 ops (5,529,600 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14: 1,382,400 ops (1,382,400 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 15: 322,560 ops (322,560 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16: 34,560 ops (34,560 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 17: 2,764,800 ops (2,764,800 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18: 691,200 ops (691,200 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 19: 161,280 ops (161,280 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 20: 17,280 ops (17,280 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 336,096 bytes out of 442,368 bytes total (76.0%)
  Bias memory:   416 bytes out of 2,048 bytes total (20.3%)
*/

